# Generated by Django 3.2.14 on 2022-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(verbose_name=int)),
                ('address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=11)),
            ],
        ),
    ]
