# Generated by Django 3.2.14 on 2022-11-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
