# Generated by Django 3.2.14 on 2022-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_place_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='MyPerson',
        ),
    ]
