# Generated by Django 3.2.14 on 2022-10-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20221003_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
