# Generated by Django 3.2.14 on 2022-10-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_myperson_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myperson',
            options={'ordering': ['last_name']},
        ),
    ]
