# Generated by Django 3.2.14 on 2022-10-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormFromModel', '0002_alter_author_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorname',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='book_name',
        ),
    ]
